### ISSUE TITLE
Bug with interpreting tables

### ISSUE THREAD

**Issue by undera** [Amaury/SkrivMarkup#20]
Hi,

I've met an issue trying to use your markup renderer with following wiki text:
|| _Pragma_   || _Value_  ||
|| #summary   || One-line summary of the page ||
|| #labels    || Comma-separated list of labels (filled in automatically via the web UI) ||

I have the error:
PHP Error with code 2: strpos(): Offset not contained in string

**Comment by Amaury** [comment]
Hi,

Thank you for your report.

In fact, tables are not "bordered". So you don't need to write the extra double-pipes.
I tried your example; without the "||" at the end of the lines, it works as it should.

But the parser shouldn't generate a PHP error in this case  :-)

Regards,

Amaury

**Comment by Amaury** [comment]
Corrected by the last push.
