### ISSUE TITLE
Anchor syntax causes error

### ISSUE THREAD

**Issue by undera** [Amaury/SkrivMarkup#21]
When I enter following text into online Skriv (http://markup.skriv.org/online/try), I get HTTP 500 error:
  ~~test~~

**Comment by Amaury** [comment]
Woops, anchors are still in the source code, but they are not of the SkrivML official syntax. So they are not tested anymore, and would be removed some day...

**Comment by undera** [comment]
I disagree that you closed the issue. It should not be closed until actual fix, because you have a problem in your parser now. If any user,  intentionally or not, will use buggy sequence, he will receive an error. This is current bug for you.

**Comment by Amaury** [comment]
Yes, you're right  :-)

**Comment by Amaury** [comment]
Corrected by the last push.
