### ISSUE TITLE
Make Scriv compatible with Github

### ISSUE THREAD

**Issue by pimpin** [Amaury/SkrivMarkup#26]
Hi,
I discover Skriv though Atoum doc.
I do not want to juge the quality of Skriv ML but give an advise :
I don't think it could survive without users and the best way to reach them is making it compatible with theirs tools.
Do you consider making a PR [here](https://github.com/github/markup#contributing) ?

Best

Pierre

**Comment by Amaury** [comment]
Yes, I considered it. But unfortunately I saw a comment on a PR, stating that [they don't accept any new contribution](https://github.com/github/markup/pull/152#issuecomment-8042433)...
