### ISSUE TITLE
Non-inline hyperlinks

### ISSUE THREAD

**Issue by jonashaag** [Amaury/SkrivMarkup#27]
There should be a way to put hyperlink references on the bottom of the page/section, similar to how reStructuredText does it.

The example on http://markup.skriv.org/online/try is terribly cluttered with hyperlinks that makes the text unreadable. Markup text should be readable by humans, not only machines.

**Comment by Amaury** [comment]
Thanks for your message. As you can guess, I tought about that.

Please, take a look at the [SkrivML's rationale](http://markup.skriv.org/language/intro#rationale).
- Lightweight markup languages should stay lightweight.
- It is designed to be fast to type. (...) It is more important to be able to write these pages quickly than to keep the likeness of any text file.
- (...) all the syntax is context-free. As you write your text, you type the markups you need when you need them, and that's it.

You can also read the [links syntax's reasoning](http://markup.skriv.org/language/syntax#links).

**Comment by jonashaag** [comment]
Well if you prefer your code the "quickly written, sacrificing readability" way, then this reasoning makes perfect sense.

**Comment by Amaury** [comment]
Yes, as for MediaWiki, Creole, Asciidoc, DokuWiki, MoinMoin, ...
SkrivML is not ascii art (like Markdown can be).
